workdir: "/home/jana/Documents/1Projects/HoneybeeDemo/"
species: "Apis mellifera"
ploidy: "1"
noChromosomes: 2
vcfDir: "/home/jana/Documents/1Projects/HoneybeeDemo/Data/RawVCF/"
bcftoolsModule: "igmm/apps/bcftools/1.9"
ancestralAllele: "/home/jana/Documents/1Projects/HoneybeeDemo/Data/AncestralAlleleVcf.txt"
meta: "/home/jana/Documents/1Projects/HoneybeeDemo/Data/Meta.csv"
chromosome_length:
  1 : 100000
  2 : 100000
